export AWS_PROFILE=pfc
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_50_cnn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_50_avg_nn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_50_nb.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_50_conv_lstm.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_50_svm.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_50_rnn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_50_stacked_rnn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_50_sepcnn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_100_cnn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_100_avg_nn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_100_nb.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_100_conv_lstm.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_100_svm.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_100_rnn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_100_stacked_rnn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_100_sepcnn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_300_cnn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_300_avg_nn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_300_nb.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_300_conv_lstm.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_300_svm.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_300_rnn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_300_stacked_rnn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_300_sepcnn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_600_cnn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_600_avg_nn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_600_nb.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_600_conv_lstm.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_600_svm.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_600_rnn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_600_stacked_rnn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_600_sepcnn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_1000_cnn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_1000_avg_nn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_1000_nb.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_1000_conv_lstm.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_1000_svm.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_1000_rnn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_1000_stacked_rnn.sh
aws ec2 run-instances --cli-input-json file://instance.json --user-data file://setup_1000_sepcnn.sh